---
title: "INFO"
output: html_document
---

```{r setup, include=FALSE}
library("dplyr")
library('rsconnect')
library("maps")
library("mapproj")
library("plyr")
library("httr")
library("jsonlite")
library("knitr")
library("ggplot2")
library("tidyr")
library("mapdata")
library("plotly")
knitr::opts_chunk$set(echo = F)
crime <- read.csv("crime_dataset.csv", stringsAsFactors = F)
```

```{r, echo = FALSE, warning = FALSE}



total.crime <- ddply(crime, c("State"), function(x){
  sum.inc <- sum(x$Incident)
  data.frame(sum.incident = sum.inc)
})


total.crime$State <- tolower(total.crime$State)
states <- map_data("state")
map.df<-merge(states, total.crime, by.x = "region", by.y = "State", all.x=T)
map.df <- map.df[order(map.df$order),]
ggplot(map.df, aes(x=long,y=lat,group=group))+
  geom_polygon(aes(fill=sum.incident))+
  geom_path()+ ggtitle("Crime in the US")+
  scale_fill_gradientn(colours=rev(heat.colors(12)),na.value="grey90")+
  coord_map()+theme_minimal()
```

```{r, echo=FALSE, fig.height=8, fig.width=6, warning=FALSE}
ggplot(crime,aes(x=Perpetrator.Ethnicity,fill=Victim.Ethnicity)) + geom_bar()
```

```{r, echo=FALSE, fig.height=8, fig.width=10, warning=FALSE}

gg3 <- ggplot(crime) +
  geom_bar(aes(x=Perpetrator.Race, fill = Weapon)) 
gg3
``````

